* Yadirmenu

** What the "Yadirmenu" name means:

"Yadirmenu" stands for "Yet Another Dirmenu."

** Why:

The goal of creating Yadirmenu was to provide a simple menu interface
that can be run on different platforms as a frontend for user scripts
and/or documents.

Currently, Yadirmenu can be used on the following platforms:

- Linux
- Termux (Terminal for Android)
- Possibly Windows (although it has not been tested)

** What:

Yadirmenu is designed to create a menu for a set of user scripts and
documents. Given a directory tree, Yadirmenu generates a menu where
directories are represented as submenus and scripts are represented as
menu items.

With this menu, users can:

- Navigate through menus and submenus.
- Execute scripts represented as menu items.
- Exit the menu.

** How:

*** Yadirmenu working logic
The user creates a directory containing subdirectories for submenus
and scripts for menu items.

To run Yadirmenu, the user executes the command, specifying the menu
directory and interface type:

#+BEGIN_SRC sh
yadirmenu --menu_dir "/path/to/menu/dir" --interface "Interface type"
#+END_SRC

where "Interface type" can be one of:
- "MenuConsole": It uses the old, reliable plain console print/read interface.
- "MenuDialog": It utilizes the console "Dialog" library.
- "MenuTk": It employs the Tkinter Python GUI library.

*** Customization Options

Yadirmenu offers customization options to tailor the menu appearance
and item names according to user preferences. These options are
defined within special files named ".META" located within each
directory.

*** Directory Metadata

Every directory can contain a ".META" file, which dictates the display
title and item names within the menu. The ".META" file structure is as
follows:

#+BEGIN_SRC sh
TITLE="Menu/Documents"
ITEM_NAME="Documents"
#+END_SRC

- The "TITLE" value is used as a menu title line.
- The "ITEM_NAME" value is used as a submenumenu item name.

In the root directory the ".META" file contains the "TITLE" field
only.

*** Script Customization:

Script files can include a special line to customize the menu item
name:

#+BEGIN_SRC sh
#MENU_ITEM_NAME="Menu item text"
#+END_SRC

- The value of the "MENU_ITEM_NAME" is used as a menu item name for
  the script.
- If this line is not present, the script file name is used as the
  item name.

Naming Convention

Script and subdirectory names follow a specific format:

#+BEGIN_SRC sh
"XX_script_file_name"
#+END_SRC

- "XX" represents a number used for sorting menu items.

** Requirements

- python3
- pythondialog
- python-dotenv

** Installation (using virtualenv)

#+BEGIN_SRC sh
    mkdir yadirmenu
    cd yadirmenu
    git clone https://github.com/ekazanov/yadirmenu.git
    python3 -m venv ./venv
    source ./venv/bin/activate
    python3 -m pip install --upgrade pip
    cd yadirmenu; pip install .
#+END_SRC

** Invocation

#+BEGIN_SRC sh
  cd yadirmenu
  source ./venv/bin/activate
  yadirmenu --menu_dir "/path/to/menu/dir" --interface "Interface type"
#+END_SRC

** Usage Tips

*** Linux

On Linux, I bind a script starting Yadirmenu to some shortcut keys. My
favorite binding keys are "Alt-Ctrl-1". On Linux, I use the "MenuTk"
interface type.

*** Termux

On Termux, I use a TermuxWidget to run the Termux console and a
"Yadirmenu". On Termux, I use the “MenuDialog” interface type.
